defaults:
  - single_arm_one_iphone_30fps@_here_
  - _self_

name: single_right_arm_pick_and_place_s1_image_only

image_shape: [3, 240, 320]

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    left_wrist_img:
      shape: ${task.image_shape}
      type: rgb
    left_robot_tcp_pose:
      shape: [9]
      type: low_dim
    left_robot_gripper_width:
      shape: [1]
      type: low_dim
  action:
    shape: [10]

env_runner:
  _target_: diffusion_policy.env_runner.real_pick_and_place_image_runner.RealPickAndPlaceImageRunner
  eval_episodes: 10
  max_duration_time: 60
  use_relative_action: True
  tcp_action_update_interval: 10
  gripper_action_update_interval: 12
  latency_step: 3
  gripper_latency_step: 3
  control_fps: 10
  inference_fps: 5
  obs_temporal_downsample_ratio: 3
  n_obs_steps: ${n_obs_steps}
  task_name: ${task_name}
  transform_params: ${task.transforms}
  shape_meta: *shape_meta
  tcp_pos_clip_range: [[0.4, -0.05, 0.45], [0.65, 0.3, 0.7]]
  tcp_rot_clip_range: [[-2.75, 0.3, -3.0], [-2.0, 0.85, -2.5]]
  tcp_ensemble_buffer_params:
    ensemble_mode: 'new'
  gripper_ensemble_buffer_params:
    ensemble_mode: 'new'
  enable_video_recording: False
  vcamera_server_ip: 192.168.2.187
  vcamera_server_port: 8102
  env_params:
    robot_server_ip: ${task.robot_server.host_ip}
    robot_server_port: ${task.robot_server.port}
    device_mapping_server_ip: ${task.device_mapping_server.host_ip}
    device_mapping_server_port: ${task.device_mapping_server.port}
    data_processing_params:
      # TODO: fix this (support left or right)
      mode: 'single_arm_one_realsense'
      use_6d_rotation: True
      debug: False
    max_fps: 30
    debug: False
    # gripper control params
    use_force_control_for_gripper: ${task.teleop_server.use_force_control_for_gripper}
    max_gripper_width: ${task.teleop_server.max_gripper_width}
    min_gripper_width: ${task.teleop_server.min_gripper_width}
    grasp_force: ${task.teleop_server.grasp_force}
    gripper_control_time_interval: ${task.teleop_server.gripper_control_time_interval}
    gripper_control_width_precision: ${task.teleop_server.gripper_control_width_precision}
    gripper_width_threshold: 0.046
    enable_gripper_width_clipping: True
  debug: False

dataset:
  _target_: diffusion_policy.dataset.cloud_pick_and_place_image_dataset.CloudPickAndPlaceImageDataset
  shape_meta: *shape_meta
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  n_latency_steps: ${n_latency_steps}
  seed: 42
  val_ratio: 0.00
  max_train_episodes: null
  delta_action: False
  relative_action: True
  # cloud and data processing params
  datacloud_endpoint: http://127.0.0.1:8083
  identifier: pick and place
  use_data_filtering: False
  use_absolute_action: True
  action_dim: 10
  temporal_downsample_ratio: 0
  temporal_upsample_ratio: 0
  use_dino: False
