defaults:
  - single_arm_real_robot_env@_here_
  - _self_
teleop_server:
  use_force_control_for_gripper: &use_force_control_for_gripper False
  max_gripper_width: &max_gripper_width   0.1
  min_gripper_width: &min_gripper_width 0.0
  gripper_control_time_interval: &gripper_control_time_interval 10  # 30 for Flexiv Gripper, 20 for PGC-50 gripper
  gripper_control_width_precision: &gripper_control_width_precision 0.01  # 0.01 for PGC-50 gripper, 0.01 for Flexiv Grav Gripper
  enable_tcp_gripper_compensation: &enable_tcp_gripper_compensation True
  tcp_gripper_compensation: &tcp_gripper_compensation [[0, 0], [1, -0.1]]
publisher:
  realsense_camera_publisher: []
  usb_camera_publisher: []
  capture_card_camera_publisher: 
    - camera_type: 'capture_card'
      camera_name: 'left_wrist_camera'
      # rgb_resolution: [1920, 1080]
      fps: 30
      cpu_core_id:
        - 11